server.server-header=
spring.config.import=file:./secrets.properties
jwt.expiration-ms=3600000
spring.h2.console.enabled=true
rate-limit.login.max-requests=30
rate-limit.api.max-requests=300
rate-limit.window-ms=60000
spring.rabbitmq.host=rattlesnake.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.ssl.enabled=true
spring.jpa.open-in-view=false
