server.server-header=
spring.config.import=file:./secrets.properties
jwt.expiration-ms=3600000
spring.h2.console.enabled=true
spring.rabbitmq.host=rattlesnake.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.ssl.enabled=true