jwt.secret=change-this-to-a-long-random-string-at-least-32-characters-for-hs256
jwt.expiration-ms=3600000

spring.h2.console.enabled=true

spring.rabbitmq.host=rattlesnake.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=ypntpiyi
spring.rabbitmq.virtual-host=ypntpiyi
spring.rabbitmq.password=wmGTqud3RURPqYS-wlRWO2ybimYooEwt
spring.rabbitmq.ssl.enabled=true